### ISSUE TITLE
Notifications not working if longer delay set.

### ISSUE THREAD

**Issue by Tadynas** [hippogamesunity/SimpleAndroidNotificationsPublic#60]
Hello,
Notifications are working when delay is less than 10 minutes, but if there is a longer delay then notifications will not be shown.

**Comment by emaadgh** [comment]
I also have this issue but only in Android 9.

**Comment by Tadynas** [comment]
I fixed by writting Timestamp.Hours instead of Timestamp.Seconds.

**Comment by emaadgh** [comment]
> I fixed by writing Timestamp.Hours instead of Timestamp.Seconds.

Did you test it also in Android 9? because I tried Timestamp.Hours and still not working.

**Comment by Tadynas** [comment]
I don't know if it works on Android 9.0, but with Android 8.0 it helped.

**Comment by hippogamesunity** [comment]
Hi! Just got Mi 9 SE with Android 9, so I was able to test it. Got it working with 10/30s intervals. I can only note that with ExecuteMode = NotificationExecuteMode.Inexact notifications become more unstable and can be shown with unstable delays (sorry for obsolete comment about inexact mode, repeated notifications can be exact). Also, If you set such short delays like 10/30s, notifications are also shown not preciously (in my case I can see 7 notifications and then they stopped adding before running the app again).

I've also updatet Troubleshooting page, so you can refer to it: https://github.com/hippogamesunity/SimpleAndroidNotificationsPublic/wiki/Troubleshooting

![image](https://user-images.githubusercontent.com/7318172/58532709-030f1e00-81ef-11e9-9a9c-1b313bac5e6c.png)
